name: R Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages("testthat")
          install.packages("your_dependencies")

      - name: Run tests
        run: Rscript -e 'testthat::test_dir("tests/testthat")'
